// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TmtInventoryApp.Data;

#nullable disable

namespace TmtInventoryApp.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20251203184503_UpdateVariantDisplayNames")]
    partial class UpdateVariantDisplayNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TmtInventoryApp.Models.BillingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("BillingRecords");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.BillingRecordItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BilledWeightKg")
                        .HasColumnType("TEXT");

                    b.Property<int>("BillingRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmtVariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BillingRecordId");

                    b.HasIndex("TmtVariantId");

                    b.ToTable("BillingRecordItems");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gstin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.PurchaseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shortage")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PurchaseRecords");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.PurchaseRecordItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bundles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PurchaseRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmtVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightTons")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseRecordId");

                    b.HasIndex("TmtVariantId");

                    b.ToTable("PurchaseRecordItems");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.SalesOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.SalesOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoosePieces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityBundles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalesOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmtVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("TmtVariantId");

                    b.ToTable("SalesOrderItems");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.StockEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("LoosePieces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PiecesPerBundle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityBundles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmtVariantId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WeightTons")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TmtVariantId");

                    b.ToTable("StockEntries");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.TmtVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diameter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("PredefinedBundleWeight")
                        .HasColumnType("REAL");

                    b.Property<double>("StandardLength")
                        .HasColumnType("REAL");

                    b.Property<bool>("UsePredefinedBundleWeight")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightPerMeter")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TmtVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diameter = 8,
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 0.39500000000000002
                        },
                        new
                        {
                            Id = 2,
                            Diameter = 10,
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 0.61699999999999999
                        },
                        new
                        {
                            Id = 3,
                            Diameter = 12,
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 0.88800000000000001
                        },
                        new
                        {
                            Id = 4,
                            Diameter = 16,
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 1.5800000000000001
                        },
                        new
                        {
                            Id = 5,
                            Diameter = 20,
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 2.4700000000000002
                        },
                        new
                        {
                            Id = 7,
                            Diameter = 0,
                            Name = "Wire - 20 Gauge",
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Diameter = 0,
                            Name = "Nail (BAG) - 2 Inch",
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 0.0
                        },
                        new
                        {
                            Id = 9,
                            Diameter = 0,
                            Name = "Nail (BAG) - 2.5 Inch",
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 0.0
                        },
                        new
                        {
                            Id = 10,
                            Diameter = 0,
                            Name = "Ring - 7/7",
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 0.0
                        },
                        new
                        {
                            Id = 11,
                            Diameter = 0,
                            Name = "Ring - 7/4",
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 0.0
                        },
                        new
                        {
                            Id = 12,
                            Diameter = 0,
                            Name = "Ring - 7/9",
                            PredefinedBundleWeight = 0.0,
                            StandardLength = 12.0,
                            UsePredefinedBundleWeight = false,
                            WeightPerMeter = 0.0
                        });
                });

            modelBuilder.Entity("TmtInventoryApp.Models.VirtualStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableBundles")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvailableWeightKg")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<int>("TmtVariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TmtVariantId");

                    b.ToTable("VirtualStocks");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.VirtualStockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bundles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VirtualStockId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeightKg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VirtualStockId");

                    b.ToTable("VirtualStockTransactions");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.BillingRecord", b =>
                {
                    b.HasOne("TmtInventoryApp.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.BillingRecordItem", b =>
                {
                    b.HasOne("TmtInventoryApp.Models.BillingRecord", "BillingRecord")
                        .WithMany("Items")
                        .HasForeignKey("BillingRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TmtInventoryApp.Models.TmtVariant", "TmtVariant")
                        .WithMany()
                        .HasForeignKey("TmtVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BillingRecord");

                    b.Navigation("TmtVariant");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.PurchaseRecordItem", b =>
                {
                    b.HasOne("TmtInventoryApp.Models.PurchaseRecord", "PurchaseRecord")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TmtInventoryApp.Models.TmtVariant", "TmtVariant")
                        .WithMany()
                        .HasForeignKey("TmtVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseRecord");

                    b.Navigation("TmtVariant");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.SalesOrder", b =>
                {
                    b.HasOne("TmtInventoryApp.Models.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.SalesOrderItem", b =>
                {
                    b.HasOne("TmtInventoryApp.Models.SalesOrder", "SalesOrder")
                        .WithMany("Items")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TmtInventoryApp.Models.TmtVariant", "TmtVariant")
                        .WithMany()
                        .HasForeignKey("TmtVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");

                    b.Navigation("TmtVariant");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.StockEntry", b =>
                {
                    b.HasOne("TmtInventoryApp.Models.TmtVariant", "TmtVariant")
                        .WithMany()
                        .HasForeignKey("TmtVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TmtVariant");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.VirtualStock", b =>
                {
                    b.HasOne("TmtInventoryApp.Models.TmtVariant", "TmtVariant")
                        .WithMany()
                        .HasForeignKey("TmtVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TmtVariant");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.VirtualStockTransaction", b =>
                {
                    b.HasOne("TmtInventoryApp.Models.VirtualStock", "VirtualStock")
                        .WithMany()
                        .HasForeignKey("VirtualStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirtualStock");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.BillingRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.PurchaseRecord", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.SalesOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
