// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TmtInventoryApp.Data;

#nullable disable

namespace TmtInventoryApp.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20251129123747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("TmtInventoryApp.Models.StockEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoosePieces")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PiecesPerBundle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityBundles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TmtVariantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TmtVariantId");

                    b.ToTable("StockEntries");
                });

            modelBuilder.Entity("TmtInventoryApp.Models.TmtVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Diameter")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StandardLength")
                        .HasColumnType("REAL");

                    b.Property<double>("WeightPerMeter")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TmtVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diameter = 8,
                            StandardLength = 12.0,
                            WeightPerMeter = 0.39500000000000002
                        },
                        new
                        {
                            Id = 2,
                            Diameter = 10,
                            StandardLength = 12.0,
                            WeightPerMeter = 0.61699999999999999
                        },
                        new
                        {
                            Id = 3,
                            Diameter = 12,
                            StandardLength = 12.0,
                            WeightPerMeter = 0.88800000000000001
                        },
                        new
                        {
                            Id = 4,
                            Diameter = 16,
                            StandardLength = 12.0,
                            WeightPerMeter = 1.5800000000000001
                        },
                        new
                        {
                            Id = 5,
                            Diameter = 20,
                            StandardLength = 12.0,
                            WeightPerMeter = 2.4700000000000002
                        },
                        new
                        {
                            Id = 6,
                            Diameter = 25,
                            StandardLength = 12.0,
                            WeightPerMeter = 3.8500000000000001
                        });
                });

            modelBuilder.Entity("TmtInventoryApp.Models.StockEntry", b =>
                {
                    b.HasOne("TmtInventoryApp.Models.TmtVariant", "TmtVariant")
                        .WithMany()
                        .HasForeignKey("TmtVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TmtVariant");
                });
#pragma warning restore 612, 618
        }
    }
}
